apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seed
spec:
  selector:
    matchLabels:
      app: seed
  serviceName: "polard-sf"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: seed
    spec:
      containers:
        - name: seed
          image: seed:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1.5Gi"
              cpu: "1000m"
          # ports:
          #   - containerPort: 8081
          # livenessProbe:
          #   httpGet:
          #     path: /api/health/v1/check
          #     port: 8081
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /api/health/v1/check
          #     port: 8081
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
          command: ["sh"]
          args: ["-c", "sleep infinity"]
  # volumeClaimTemplates:
  #   - metadata:
  #       name: www
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       storageClassName: "my-storage-class"
  #       resources:
  #         requests:
  #           storage: 1Gi
